// Code generated by airplane tasks gentypes. DO NOT EDIT.

export type MyTaskParams = {
  "date-time": string;
  config_var: { name: string; value: string };
  date: string;
  float: number;
  int: number;
  string: string;
  upload: { __airplaneType: "upload"; id: string; url: string };
};
