package gentypes

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/MakeNowJust/heredoc"
	"github.com/airplanedev/cli/pkg/api"
	"github.com/airplanedev/cli/pkg/cli"
	"github.com/airplanedev/cli/pkg/cmd/auth/login"
	"github.com/airplanedev/cli/pkg/logger"
	"github.com/airplanedev/cli/pkg/utils"
	libapi "github.com/airplanedev/lib/pkg/api"
	"github.com/airplanedev/lib/pkg/build"
	"github.com/airplanedev/lib/pkg/deploy/taskdir"
	"github.com/airplanedev/lib/pkg/deploy/taskdir/definitions"
	"github.com/airplanedev/lib/pkg/utils/fsx"
	"github.com/pkg/errors"
	"github.com/spf13/cobra"
)

type config struct {
	root     *cli.Config
	taskSlug string
	taskDef  string
	envSlug  string
	fileName string
}

func New(c *cli.Config) *cobra.Command {
	var cfg = config{root: c}

	cmd := &cobra.Command{
		Use:   "gentypes slug",
		Short: "Generates types for Node.js task parameters",
		Long: `Generates TypeScript types for Node.js task parameters.
		If no task is provided, a file with types for all Node.js tasks is produced.
		If a task is provided, a file with types for that task is produced.
		If a task definition file (*.task.yaml) is provided, a type will be generated at the top of the task script.`,
		Example: heredoc.Doc(`
			airplane gentypes
			airplane gentypes my_task
			airplane gentypes 
		`),
		PersistentPreRunE: utils.WithParentPersistentPreRunE(func(cmd *cobra.Command, args []string) error {
			return login.EnsureLoggedIn(cmd.Root().Context(), c)
		}),
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				if definitions.IsTaskDef(args[0]) {
					cfg.taskDef = args[0]
				} else {
					cfg.taskSlug = args[0]
				}
			}
			return run(cmd.Root().Context(), cfg)
		},
	}

	cmd.Flags().StringVar(&cfg.envSlug, "env", "", "The slug of the environment to query. Defaults to your team's default environment.")
	cmd.Flags().StringVar(&cfg.fileName, "file", "types.ts", "The file to save the generated types to.")

	return cmd
}

func run(ctx context.Context, cfg config) error {
	var wr io.Writer
	var err error
	var fileName string
	if cfg.taskDef != "" {
		if !fsx.Exists(cfg.taskDef) {
			return errors.Errorf("%s does not exist", cfg.taskDef)
		}
		wr, err = os.Create(cfg.taskDef)
		if err != nil {
			return err
		}
	} else {
		fileName = cfg.fileName
		if !strings.HasSuffix(fileName, ".ts") {
			fileName = fmt.Sprintf("%s.ts", fileName)
		}
		if fsx.Exists(fileName) {
			if ok, err := utils.Confirm(fmt.Sprintf("Would you like to overwrite %s?", fileName)); err != nil {
				return err
			} else if !ok {
				return nil
			}
		}
		wr, err = os.Create(fileName)
		if err != nil {
			errors.Wrapf(err, "creating file %s", fileName)
		}
	}

	if err := genTypeScriptTypes(ctx, cfg.root.Client, cfg.envSlug, genTypeScriptTypesOpts{
		taskSlug: cfg.taskSlug,
		taskDef:  cfg.taskDef,
		wr:       wr,
	}); err != nil {
		return err
	}

	if fileName != "" {
		logger.Log("Generated TypeScript types at %s", fileName)
	} else {
		logger.Log("Generated TypeScript types")
	}
	return nil
}

type genTypeScriptTypesOpts struct {
	taskSlug string
	taskDef  string
	wr       io.Writer
}

func genTypeScriptTypes(ctx context.Context, apiClient api.APIClient, envSlug string, opts genTypeScriptTypesOpts) error {
	var tasks []libapi.Task
	var contentToOverwrite string
	if opts.taskSlug != "" {
		task, err := apiClient.GetTask(ctx, libapi.GetTaskRequest{
			Slug:    opts.taskSlug,
			EnvSlug: envSlug,
		})

		if err != nil {
			return err
		}
		tasks = append(tasks, task)
	} else if opts.taskDef != "" {
		dir, err := taskdir.Open(opts.taskDef)
		if err != nil {
			return err
		}
		defer dir.Close()

		def, err := dir.ReadDefinition()
		if err != nil {
			return err
		}
		entrypoint, err := def.Entrypoint()
		if err != nil {
			return err
		}
		entrypointContent, err := ioutil.ReadFile(entrypoint)
		if err != nil {
			return err
		}
		contentToOverwrite = string(entrypointContent)

		utr, err := def.GetUpdateTaskRequest(ctx, apiClient)
		if err != nil {
			return err
		}

		tasks = []libapi.Task{
			{
				Slug:       def.GetSlug(),
				Kind:       utr.Kind,
				Parameters: utr.Parameters,
			},
		}
	} else {
		tasksResp, err := apiClient.ListTasks(ctx, envSlug)
		if err != nil {
			return err
		}
		tasks = tasksResp.Tasks
	}

	var buff bytes.Buffer
	if contentToOverwrite == "" {
		fmt.Fprint(&buff, "// Code generated by airplane tasks gentypes. DO NOT EDIT.\n\n")
	}
	for _, task := range tasks {
		if task.Kind != build.TaskKindNode {
			continue
		}
		paramTypes := make(map[string]string)
		for _, param := range task.Parameters {
			t, err := toTypeScriptType(param.Type)
			if err != nil {
				return err
			}
			paramTypes[param.Slug] = t
		}

		var params []string
		for slug, paramType := range paramTypes {
			if strings.Contains(slug, "-") {
				slug = fmt.Sprintf("\"%s\"", slug)
			}
			params = append(params, fmt.Sprintf("%s: %s;", slug, paramType))
		}
		sort.Strings(params)

		tc := templateConfig{
			TaskName:   strings.Title(strings.ReplaceAll(task.Name, " ", "")),
			TaskParams: strings.Join(params, "\n  "),
		}

		t := paramTypesTemplate
		if len(params) == 0 {
			t = paramTypesTemplateNoParams
		}
		tmpl, err := template.New("paramTypes").Parse(t)
		if err != nil {
			return err
		}
		err = tmpl.Execute(&buff, tc)
		if err != nil {
			return err
		}
	}

	if 
	_, err := opts.wr.Write(buff.Bytes())

	return err
}

func toTypeScriptType(t libapi.Type) (string, error) {
	switch t {
	case libapi.TypeBoolean:
		return "boolean", nil
	case libapi.TypeString:
		return "string", nil
	case libapi.TypeInteger, libapi.TypeFloat:
		return "number", nil
	case libapi.TypeDate, libapi.TypeDatetime:
		return "string", nil
	case libapi.TypeUpload:
		return fileType, nil
	case libapi.TypeConfigVar:
		return configType, nil
	}
	return "", errors.Errorf("unknown type %s", t)
}
