name: release

on:
  push:
    tags:
      - "v*"

env:
  GOOGLE_CREDENTIALS_FILE_PATH: .google_credentials

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Set up gcloud CLI
        uses: google-github-actions/auth@v1
        with:
          project_id: airplane-prod
          credentials_json: ${{ secrets.GCP_KEY }}
          create_credentials_file: true
          export_environment_variables: true
      - uses: google-github-actions/setup-gcloud@v1.1.0
      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
