name: test-release
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v4
        with:
          args: build --snapshot --rm-dist --timeout 20m
        env:
          GITHUB_TOKEN: test
          SEGMENT_WRITE_KEY: test
          SENTRY_DSN: test
